// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// Article defines model for Article.
type Article struct {
	AmountOf string `json:"amount_of"`
	ArtId    string `json:"art_id"`
}

// Inventory defines model for Inventory.
type Inventory struct {
	Inventory *[]Stock `json:"inventory,omitempty"`
}

// Message defines model for Message.
type Message struct {
	Message string `json:"message"`
}

// Order defines model for Order.
type Order struct {
	Number      int    `json:"number"`
	ProductName string `json:"product_name"`
}

// Product defines model for Product.
type Product struct {
	ContainArticles *[]Article `json:"contain_articles,omitempty"`
	Name            string     `json:"name"`
}

// ProductStock defines model for ProductStock.
type ProductStock struct {
	Product Product `json:"product"`
	Stock   int     `json:"stock"`
}

// ProductStocks defines model for ProductStocks.
type ProductStocks struct {
	Products *[]ProductStock `json:"products,omitempty"`
}

// Products defines model for Products.
type Products struct {
	Products *[]Product `json:"products,omitempty"`
}

// SellOrder defines model for SellOrder.
type SellOrder struct {
	Orders []Order `json:"orders"`
}

// Stock defines model for Stock.
type Stock struct {
	ArtId string `json:"art_id"`
	Name  string `json:"name"`
	Stock string `json:"stock"`
}

// UpsertInventoryJSONBody defines parameters for UpsertInventory.
type UpsertInventoryJSONBody Inventory

// UpsertProductsJSONBody defines parameters for UpsertProducts.
type UpsertProductsJSONBody Products

// SellFromInventoryJSONBody defines parameters for SellFromInventory.
type SellFromInventoryJSONBody SellOrder

// UpsertInventoryJSONRequestBody defines body for UpsertInventory for application/json ContentType.
type UpsertInventoryJSONRequestBody UpsertInventoryJSONBody

// UpsertProductsJSONRequestBody defines body for UpsertProducts for application/json ContentType.
type UpsertProductsJSONRequestBody UpsertProductsJSONBody

// SellFromInventoryJSONRequestBody defines body for SellFromInventory for application/json ContentType.
type SellFromInventoryJSONRequestBody SellFromInventoryJSONBody
